# Generated by Django 3.2.8 on 2021-10-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211014_1758'),
        ('main', '0002_auto_20211021_1237'),
    ]

    operations = [
    ]
