# Generated by Django 3.2.8 on 2021-10-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_0002_auto_20211014_1758_0002_auto_20211021_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.customuser'),
            preserve_default=False,
        ),
    ]
