# Generated by Django 3.2.8 on 2021-10-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_authorkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_favicon',
            field=models.ImageField(default='/static/pyth_to_img/img.jpg', upload_to=None),
        ),
    ]
