# Generated by Django 3.2.8 on 2021-10-30 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211030_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='addressee',
            field=models.ManyToManyField(related_name='addressee_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
